/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#e0e2ef",
        "secondary": "#44e2cd",
        "secondary-fixed-dim": "#3cddc7",
        "surface-dim": "#10131c",
        "on-tertiary": "#502400",
        "outline": "#8c909f",
        "on-primary-container": "#00285d",
        "inverse-primary": "#005ac2",
        "on-tertiary-fixed": "#311400",
        "inverse-on-surface": "#2d303a",
        "background": "#10131c",
        "primary-fixed": "#d8e2ff",
        "on-error": "#690005",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed-dim": "#ffb786",
        "primary": "#adc6ff",
        "surface-container-highest": "#32343f",
        "outline-variant": "#424754",
        "surface-variant": "#32343f",
        "surface": "#10131c",
        "on-surface-variant": "#c2c6d6",
        "tertiary-container": "#df7412",
        "surface-container-high": "#272a34",
        "on-surface": "#e0e2ef",
        "primary-container": "#4d8eff",
        "secondary-fixed": "#62fae3",
        "surface-container": "#1c1f29",
        "tertiary": "#ffb786",
        "secondary-container": "#03c6b2",
        "on-tertiary-container": "#461f00",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#181b25",
        "primary-fixed-dim": "#adc6ff",
        "on-secondary": "#003731",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ffdcc6",
        "inverse-surface": "#e0e2ef",
        "surface-tint": "#adc6ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0b0e17",
        "surface-bright": "#363943",
        "on-secondary-fixed-variant": "#005047",
        "on-primary": "#002e6a",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-container": "#004d44",
        "on-secondary-fixed": "#00201c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
        technical: ["IBM Plex Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
