export const FACTORY_ABI = [
  { inputs: [{ internalType: "string", name: "_name", type: "string" }, { internalType: "string", name: "_emoji", type: "string" }, { internalType: "string", name: "_adminName", type: "string" }], name: "createGroup", outputs: [{ internalType: "address", name: "vault", type: "address" }], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "getGroups", outputs: [{ components: [{ internalType: "address", name: "vault", type: "address" }, { internalType: "string", name: "name", type: "string" }, { internalType: "string", name: "emoji", type: "string" }, { internalType: "address", name: "admin", type: "address" }, { internalType: "uint256", name: "createdAt", type: "uint256" }], internalType: "struct ChainSplitFactory.GroupInfo[]", name: "", type: "tuple[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "_user", type: "address" }], name: "getUserGroups", outputs: [{ internalType: "address[]", name: "", type: "address[]" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "groupCount", outputs: [{ internalType: "uint256", name: "", type: "uint256" }], stateMutability: "view", type: "function" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "vault", type: "address" }, { indexed: true, internalType: "address", name: "admin", type: "address" }, { indexed: false, internalType: "string", name: "name", type: "string" }], name: "GroupCreated", type: "event" },
] as const;

export const VAULT_ABI = [
  { inputs: [], name: "getGroupInfo", outputs: [{ internalType: "string", name: "name", type: "string" }, { internalType: "string", name: "emoji", type: "string" }, { internalType: "address", name: "groupAdmin", type: "address" }, { internalType: "uint256", name: "memberCount", type: "uint256" }, { internalType: "uint256", name: "totalExpenses", type: "uint256" }, { internalType: "bool", name: "settled", type: "bool" }, { internalType: "uint256", name: "balance", type: "uint256" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getMembers", outputs: [{ internalType: "address[]", name: "", type: "address[]" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getExpenses", outputs: [{ components: [{ internalType: "uint256", name: "id", type: "uint256" }, { internalType: "string", name: "name", type: "string" }, { internalType: "uint256", name: "amount", type: "uint256" }, { internalType: "address", name: "paidBy", type: "address" }, { internalType: "uint8", name: "category", type: "uint8" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "bool", name: "isEqual", type: "bool" }, { internalType: "address[]", name: "splitAmong", type: "address[]" }, { internalType: "uint256[]", name: "shares", type: "uint256[]" }, { internalType: "bool", name: "isDeleted", type: "bool" }], internalType: "struct GroupVault.Expense[]", name: "", type: "tuple[]" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "calculateSettlements", outputs: [{ internalType: "address[]", name: "froms", type: "address[]" }, { internalType: "address[]", name: "tos", type: "address[]" }, { internalType: "uint256[]", name: "amounts", type: "uint256[]" }], stateMutability: "view", type: "function" },
  { inputs: [], name: "getSettlements", outputs: [{ components: [{ internalType: "address", name: "from", type: "address" }, { internalType: "address", name: "to", type: "address" }, { internalType: "uint256", name: "amount", type: "uint256" }, { internalType: "uint256", name: "timestamp", type: "uint256" }, { internalType: "bool", name: "executed", type: "bool" }], internalType: "struct GroupVault.Settlement[]", name: "", type: "tuple[]" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "_member", type: "address" }], name: "getMemberNetBalance", outputs: [{ internalType: "int256", name: "netBalance", type: "int256" }], stateMutability: "view", type: "function" },
  { inputs: [{ internalType: "address", name: "_wallet", type: "address" }, { internalType: "string", name: "_name", type: "string" }], name: "addMember", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "string", name: "_name", type: "string" }, { internalType: "uint256", name: "_amount", type: "uint256" }, { internalType: "address", name: "_paidBy", type: "address" }, { internalType: "uint8", name: "_category", type: "uint8" }, { internalType: "address[]", name: "_splitAmong", type: "address[]" }], name: "addExpenseEqual", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "string", name: "_name", type: "string" }, { internalType: "uint256", name: "_amount", type: "uint256" }, { internalType: "address", name: "_paidBy", type: "address" }, { internalType: "uint8", name: "_category", type: "uint8" }, { internalType: "address[]", name: "_splitAmong", type: "address[]" }, { internalType: "uint256[]", name: "_shares", type: "uint256[]" }], name: "addExpenseCustom", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "uint256", name: "_expenseId", type: "uint256" }], name: "deleteExpense", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "_to", type: "address" }], name: "settleDebt", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [], name: "deposit", outputs: [], stateMutability: "payable", type: "function" },
  { inputs: [], name: "markGroupSettled", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [], name: "withdrawRemaining", outputs: [], stateMutability: "nonpayable", type: "function" },
  { inputs: [{ internalType: "address", name: "" , type: "address" }], name: "members", outputs: [{ internalType: "address", name: "wallet", type: "address" }, { internalType: "string", name: "displayName", type: "string" }, { internalType: "uint256", name: "deposited", type: "uint256" }, { internalType: "uint256", name: "totalShare", type: "uint256" }, { internalType: "bool", name: "isActive", type: "bool" }], stateMutability: "view", type: "function" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "uint256", name: "expenseId", type: "uint256" }, { indexed: false, internalType: "string", name: "name", type: "string" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }, { indexed: false, internalType: "address", name: "paidBy", type: "address" }], name: "ExpenseAdded", type: "event" },
  { anonymous: false, inputs: [{ indexed: true, internalType: "address", name: "from", type: "address" }, { indexed: true, internalType: "address", name: "to", type: "address" }, { indexed: false, internalType: "uint256", name: "amount", type: "uint256" }], name: "SettlementExecuted", type: "event" },
] as const;

export const FACTORY_ADDRESS = (
  import.meta.env.VITE_NETWORK === "mainnet"
    ? import.meta.env.VITE_FACTORY_ADDRESS_MAINNET
    : import.meta.env.VITE_FACTORY_ADDRESS
) as `0x${string}`;
